---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================

# child
- name: Sysprep run to individualize Machine
  hosts: sysprep
  roles:
    - { role: 'settings/sysprep', tags: 'sysprep'}

